name: Update README

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 


      - name: Calculate progress and update README
        run: |
          DIFF_OUTPUT=$(diff -u "Pure Map.map" "Current Map.map" || true)

          ADDED_LINES=$(echo "$DIFF_OUTPUT" | grep -c '^+')

          DELETED_LINES=$(echo "$DIFF_OUTPUT" | grep -c '^-')

          TOTAL_CHANGED_LINES=$((ADDED_LINES - DELETED_LINES))

          echo "Added lines: $ADDED_LINES"
          echo "Deleted lines: $DELETED_LINES"
          echo "Total changed lines: $TOTAL_CHANGED_LINES"

          TOTAL_FUNCTIONS=6297

          PROGRESS=$((TOTAL_CHANGED_LINES * 100 / TOTAL_FUNCTIONS))

          README_CONTENTS=$(cat README.md)

          UPDATED_CONTENTS=$(echo "$README_CONTENTS" | sed "s/Reversing%20Progress-[0-9]*%25-blue.svg/Reversing%20Progress-$PROGRESS%25-blue.svg/")

          echo "$UPDATED_CONTENTS" > README.md
          echo "Original README contents:"

          cat README.md

          echo "New README contents:"
          echo "$UPDATED_CONTENTS"

          echo "$UPDATED_CONTENTS" > README.md
          git add README.md

          echo "Changes to commit:"
          git status

          git commit -m "Update README with progress" -m "Changed lines: $TOTAL_CHANGED_LINES" || echo "No changes to commit"
          git push


      - name: Commit and push if changed
        run: |
          git config user.email "actions@users.noreply.github.com"
          git config user.name "GitHub Actions"
          git add README.md
          git commit -m "Update README with progress" -m "Changed lines: $CHANGED_LINES" || echo "No changes to commit"
          git push